[package]
name = "trigger-thief"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
rfd = "0.10.0"
aoe2-probe = "0.2.13"